project:
  type: book
book:
  title: "Beyond the average treatment effect"
  subtitle: "Risk-based approaches to medical decision making"
  author: "Alexandros Rekkas"
  chapters:
    - index.qmd
    - ch2_review.qmd
    - ch3_framework.qmd
    - ch4_simulation.qmd
    - ch5_melanoma.qmd
    - ch6_covid.qmd
    - ch7_osteoporosis.qmd
    - ch8_discussion.qmd
    - references.qmd
  appendices:
    - ch3_appendix.qmd
    - ch4_appendix.qmd
    - ch7_appendix.qmd
    - summary.qmd

bibliography: references.bib
csl: american-medical-association-alphabetical.csl

format:
  pdf:
    documentclass: book
    template-partials:
      - before-body.tex
    classoption: [10pt]
    include-in-header:
      - preamble.tex
    toc: false
    cite-method: citeproc
