project:
  type: book
book:
  title: "Baseline risk in medical decision making"
  subtitle: "From outcome prediction to the assessment of treatment effect heterogeneity"
  author: "Alexandros Rekkas"
  date: "3/19/2023"
  chapters:
    - index.qmd
    - ch1_introduction.qmd
    - ch2_review.qmd
    - ch3_framework.qmd
    - ch4_simulation.qmd
    - ch5_melanoma.qmd
    - ch6_covid.qmd
    - ch7_osteoporosis.qmd
    - ch8_discussion.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  pdf:
    documentclass: book
    include-in-header:
      - preamble.tex
    toc-depth: 1
