\pagestyle{fancy}
# Acknowledgements {.unnumbered}

I feel the obligation to express my sincere gratitude to several people, whose
help and guidance have been crucial for the completion of this
dissertation.\newline

My promotor **Prof. Peter Rijnbeek** guided my work from the start and provided
the necessary environment for completing this thesis. This work could have never
been completed without his support.\newline

My copromotor **Dr.ir. David van Klaveren** guided and supported me through the
entire process of this thesis, often going beyond the basic responsibilities of
a supervisor. I consider him to be a true mentor.\newline

My promotor **Prof. Ewout Steyerberg** provided invaluable help and suggestions
regarding the entirety of the work presented in this dissertation.\newline

My promotor at the start of this work **Prof. Johan van der Lei** welcomed me to
the department of Medical Informatics and helped me in the initial stages of my
PhD.\newline

**Prof. David Kent** provided invaluable input, especially during the initial
formative stages of my PhD.\newline

**Dr. Patrick Ryan** facilitated data access for many of the projects included
in this thesis and provided incredibly helpful input during the research phase
of my PhD.\newline

My colleagues **Egill Fridgeirsson, Henrik John, and Solomon Ioannou** became my
closest friends while working at the department of Medical Informatics. Our
discussions very often provoked me to expand my scientific and general
knowledge. They certainly made the expat life a lot easier.

\clearpage\null\pagestyle{empty}
